<?xml version="1.0" encoding="UTF-8"?>
<testrun name="PascalSuite" project="recfun" tests="4" started="4" failures="0" errors="1" ignored="0">
  <testsuite name="recfun.PascalSuite" time="0.015">
    <testcase name="pascal: col=0,row=2" classname="recfun.PascalSuite" time="0.0"/>
    <testcase name="pascal: col=1,row=2" classname="recfun.PascalSuite" time="0.0"/>
    <testcase name="pascal: col=1,row=3" classname="recfun.PascalSuite" time="0.0"/>
    <testcase name="Fibonacci" classname="recfun.PascalSuite" time="0.015">
      <error>org.scalatest.exceptions.TestFailedException: 21.0 did not equal 21.1
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:318)
	at recfun.PascalSuite.newAssertionFailedException(PascalSuite.scala:9)
	at org.scalatest.Assertions$class.assert(Assertions.scala:401)
	at recfun.PascalSuite.assert(PascalSuite.scala:9)
	at recfun.PascalSuite$$anonfun$4.apply$mcV$sp(PascalSuite.scala:24)
	at recfun.PascalSuite$$anonfun$4.apply(PascalSuite.scala:24)
	at recfun.PascalSuite$$anonfun$4.apply(PascalSuite.scala:24)
	at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1265)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1974)
	at recfun.PascalSuite.withFixture(PascalSuite.scala:9)
	at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1262)
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:198)
	at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1271)
	at recfun.PascalSuite.runTest(PascalSuite.scala:9)
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:260)
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:249)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:249)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:326)
	at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1304)
	at recfun.PascalSuite.runTests(PascalSuite.scala:9)
	at org.scalatest.Suite$class.run(Suite.scala:2303)
	at recfun.PascalSuite.org$scalatest$FunSuite$$super$run(PascalSuite.scala:9)
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:362)
	at org.scalatest.FunSuite$class.run(FunSuite.scala:1310)
	at recfun.PascalSuite.run(PascalSuite.scala:9)
	at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:94)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</error>
    </testcase>
  </testsuite>
</testrun>
